# Generated by Django 4.0.7 on 2023-01-11 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('onestop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.ManyToManyField(related_name='notes_owned', through='onestop.Note', to=settings.AUTH_USER_MODEL),
        ),
    ]
