# Generated by Django 4.0.7 on 2023-02-06 09:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0002_alter_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
