# Generated by Django 4.0.7 on 2023-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='picture',
        ),
        migrations.AddField(
            model_name='pic',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
