# Generated by Django 4.0.7 on 2023-01-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daisy', '0002_remove_pic_content_type_remove_pic_picture_pic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
