# Generated by Django 4.0.7 on 2023-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0004_comment_pic_comments_comment_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
